#!/user/bin/env bash
#configures a new server and adds a header X-server-by

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allo 'Nginx HTTP'
sudo sed -i 's/http {/&\n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/nginx.conf
sudo service nginx restart
