#!/bin/bash
total 0
drwxr-xr-x 1 kass kass 4096 Mar  3 14:53 .
drwxr-xr-x 1 kass kass 4096 Mar  3 14:46 ..
-rwxr--r-- 1 kass kass   16 Mar  3 14:47 0-current_working_directory
-rw-r--r-- 1 kass kass   12 Mar  3 14:53 1-listit
-rw-r--r-- 1 kass kass   12 Mar  3 14:47 README.md
